# Generated by Django 4.2.4 on 2023-08-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('ID_Contact', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(blank=True)),
                ('Email', models.TextField(blank=True)),
                ('Comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfContact',
            fields=[
                ('ID_Type', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('ID_Person', models.AutoField(primary_key=True, serialize=False)),
                ('Lastname', models.CharField(blank=True, max_length=100)),
                ('BirthDate', models.DateField(blank=True)),
                ('ID_Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('ID_Organization', models.AutoField(primary_key=True, serialize=False)),
                ('OrganizationType', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('FoundationDate', models.DateField(blank=True)),
                ('ID_Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.contacts')),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='ID_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonebook.typesofcontact'),
        ),
    ]
