# Generated by Django 4.2.4 on 2023-08-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Phone',
            field=models.BigIntegerField(blank=True),
        ),
    ]
